Add `mkdir unit_tests` command
csiro-wsn/ei-freertos pull request #9
Opened 2020-05-07 09:49 UTC by yanxiang-wang

The `unit_tests` folder was not in the repo. Thus, the `cpputest' would be created in the root folder.

2020-05-07 10:26 UTC, JordanYates commented
Thanks for the fix.
As provided, the script will fail the second time it is run due to the unit_test folder now existing.
`jordan@VM:~$ mkdir test`
`jordan@VM:~$ mkdir test`
`mkdir: cannot create directory ‘test’: File exists`
This can be resolved by using the -p flag on mkdir.

2020-05-07 10:27 UTC, JordanYates requested changes
Add -p flag to mkdir to only attempt directory creation if it doesn't already exist.

2020-05-07 12:06 UTC, yanxiang-wang commented
Agree. Besides, I try to rewrite the path configuration part and make it more easier to deploy.

2020-05-16 09:16 UTC, JordanYates approved these changes

2020-05-16 09:17 UTC, merged